### ISSUE TITLE
Point system & on minium player start

### ISSUE THREAD

**Issue by sjempotje** [ericyoondotcom/MinecraftManhunt#75]
## Description
Hey,

Really cool project and I'm really happy to use this, but there are 2 thing I am missing in this manhunt plugin is points & autostart. Is it possible to add points to users when they win? And idealy store them in a database like mysql or mongodb? And one last thing, I want to use this for a waterfall server and would it be possible to add some kind of whitelist when the game could be full and that the manhunt starts automatically after x amount of players?

Greetings,
Sem

**Comment by ericyoondotcom** [comment]
Hello, and thanks for your suggestion.

The plugin was not designed for automated use in mind—like most other game plugins, it was meant to be run by players. The scaffolding for automation is not currently in place (an API, a database, etc), and such features are out of the scope of the project.

With that being said, if you have experience with Java, this project's license allows you to fork the repo if you want to add these features. If you do this, I will probably not merge your changes back into this repo (since I want to keep this plugin simple), but I will point others who are looking for the same feature set to your fork.
